from pathlib import Path
from motion_design import DEFAULTS
p=DEFAULTS
params=',\n    '.join(f"{k} = {'undef' if v is None else v}" for k,v in p.items() if k!='hole_clearance')
s='''// Pegboard anchor — millimeters; X width, Y toward you, Z up.
// use <pegboard_anchor.scad>; then pegboard_anchor(board_thickness=3.94);
// Fuse your mount with the front spine at Y=spine_depth (default4.5).
// Thickness changes require a new fit/motion check. Do not scale the whole part.
// Canonical validated CAD is generated by anchor.py + motion_design.py.
$fn = 96;

module pegboard_anchor(
    PARAMS
) {
    $fn = 96;
    assert(board_thickness>0 && hole_diameter>width && width>0);
    chord_half = sqrt(hole_diameter*hole_diameter-width*width)/2;
    assert(neck_height < 2*chord_half);
    z0 = -chord_half + neck_height/2 + seat_drop;
    slope = tongue_rise/tongue_run;
    radius = neck_height/2;
    elbow = is_undef(elbow_offset) ? pull_clearance-front_gap
        -(2*chord_half-radius)/slope+radius*sqrt(1+1/(slope*slope))
        : elbow_offset;
    yrear = -board_thickness-elbow;
    chamfer = min(0.7, locator_depth*0.35, locator_height*0.3);
    zl = -pitch+z0;
    // [2D u,2D v,extrusion] -> global[Y,Z,X].
    multmatrix([[0,0,1,0],[1,0,0,0],[0,1,0,0],[0,0,0,1]])
    linear_extrude(height=width,center=true,convexity=10)
    union() {
        hull() {
            translate([1.4,z0]) circle(d=neck_height);
            translate([yrear,z0]) circle(d=neck_height);
        }
        hull() {
            translate([yrear,z0]) circle(d=neck_height);
            translate([yrear-tongue_run,z0+tongue_rise]) circle(d=neck_height);
        }
        offset(r=0.65) offset(delta=-0.65)
            translate([front_gap,4.2-spine_height])
                square([spine_depth-front_gap,spine_height]);
        polygon([
            [0.6,zl-locator_height/2],
            [-locator_depth+chamfer,zl-locator_height/2],
            [-locator_depth,zl-locator_height/2+chamfer],
            [-locator_depth,zl+locator_height/2-chamfer],
            [-locator_depth+chamfer,zl+locator_height/2],
            [0.6,zl+locator_height/2]
        ]);
    }
}

// Preview is the default anchor. use<> excludes this top-level preview.
pegboard_anchor();
'''.replace('PARAMS',params)
Path('pegboard_anchor.scad').write_text(s)
