"""Build the authored numerical audit, tables and scientific plots from completed receipts."""
from pathlib import Path
import json,hashlib,math,html,os
import numpy as np
R=Path(__file__).resolve().parents[3];B=R/'bench/reviews/key-fan-audit-v1';D=R/'docs/gallery/key-fan/studies';D.mkdir(exist_ok=True)
os.environ.setdefault('MPLCONFIGDIR',str(R/'.local-runtime/hx04-mpl-cache'))
import matplotlib;matplotlib.use('Agg')
import matplotlib.pyplot as plt
plt.rcParams.update({'font.family':'DejaVu Sans','axes.spines.top':False,'axes.spines.right':False,'axes.facecolor':'#faf8f0','figure.facecolor':'#f6f3eb','axes.labelcolor':'#253a32','text.color':'#253a32','xtick.color':'#253a32','ytick.color':'#253a32'})
def load(name):return json.loads((B/name).read_text())
def rows(r):return r['results']
def table(headers,items):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+html.escape(h)+'</th>' for h in headers)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(str(c))+'</td>' for c in row)+'</tr>' for row in items)+'</tbody></table></div>'
def save(fig,name):
 fig.tight_layout();fig.savefig(D/(name+'.png'),dpi=150);fig.savefig(B/(name+'.svg'));plt.close(fig)
 p=B/(name+'.svg');p.write_text('\n'.join(line.rstrip() for line in p.read_text().splitlines())+'\n')
h7=load('fea-h7-deep.json');h6=load('fea-h6-baseline.json');h5=load('fea-h5-baseline.json');ortho=load('fea-orthotropic-reference.json');patch2=load('fea-patch-2x.json');motion=load('motion-audit.json');install=load('install-audit.json');candidates=load('install-candidates.json');native=load('native-audit.json');hoop=load('hoop-h025.json');hoop4=load('hoop-h04.json');project=load('uncompensated-project-check.json')
case_names=[q['id'] for q in h7['results'][0]['loads']];mounts=h7['results'];mount_table=[]
for case in mounts:
 for q in case['loads']:mount_table.append([q['id'],case['support'],case['force_mode'],f"{q['max_deflection_mm']:.5f}",f"{q['work_equivalent_deflection_mm']:.5f}",f"{q['von_mises_MPa']['max']:.2f}",f"{q['von_mises_MPa']['p99']:.3f}"])
mesh_table=[]
for r in [h7,h6,h5]:mesh_table.append([r['h_requested_mm'],r['nodes'],r['elements'],f"{100*abs(r['linear_tetra_mesh_volume_mm3']-native['native_volume_mm3'])/native['native_volume_mm3']:.3f}%"])
compare=[]
for i,name in enumerate(case_names):
 values=[r['results'][0]['loads'][i]['max_deflection_mm'] for r in [h7,h6,h5]];peaks=[r['results'][0]['loads'][i]['von_mises_MPa']['max'] for r in [h7,h6,h5]];spread=(max(values)-min(values))/values[0]*100;compare.append([name,*[f'{x:.5f}' for x in values],f'{spread:.1f}%',*[f'{x:.2f}' for x in peaks]])
# Mount sensitivity: same 50 N T10 grip load, same geometry/material.
fig,ax=plt.subplots(figsize=(9,4.6));cases=mounts[1:];vals=[q['loads'][0]['max_deflection_mm'] for q in cases];labels=[q['support'] for q in cases];bars=ax.bar(labels,vals,color=['#3c9c8d','#c16d43','#6a91b4','#91b59c']);ax.set_yscale('log');ax.set_ylabel('Maximum rack displacement (mm, logarithmic axis)');ax.set_title('Mount assumptions dominate · T10 grip, 50 N downward')
for b,v in zip(bars,vals):ax.text(b.get_x()+b.get_width()/2,v*1.12,f'{v:.3f} mm',ha='center',fontsize=10)
ax.set_ylim(.04,10);save(fig,'mount-sensitivity')
fig,ax=plt.subplots(figsize=(9,4.7));x=np.arange(5);ax.bar(x-.18,[q['max_deflection_mm'] for q in mounts[0]['loads']],.36,label='Mouth force only',color='#99bba8');ax.bar(x+.18,[q['max_deflection_mm'] for q in mounts[1]['loads']],.36,label='Grip force + equivalent moment',color='#318d83');ax.set_xticks(x,['T10 down','T10 sideways','Hex10 down','T50 outward','T2 down']);ax.set_ylabel('Maximum rack displacement (mm)');ax.set_title('Body response changes when the handle lever arm is included');ax.legend(frameon=False);save(fig,'mouth-versus-grip')
fig,axes=plt.subplots(1,2,figsize=(11,4.4))
for i,name in enumerate(case_names):
 axes[0].plot([7,6,5],[r['results'][0]['loads'][i]['max_deflection_mm'] for r in [h7,h6,h5]],'-o',label=name.replace('T-handle','T'))
 axes[1].plot([7,6,5],[r['results'][0]['loads'][i]['von_mises_MPa']['max'] for r in [h7,h6,h5]],'-o')
axes[0].set_ylabel('Maximum displacement (mm)');axes[1].set_ylabel('Peak integration-point von Mises (MPa)')
for ax in axes:ax.set_xlabel('Requested mesh maximum size (mm)');ax.invert_xaxis();ax.grid(alpha=.15)
axes[0].legend(fontsize=7,frameon=False);fig.suptitle('Refinement sensitivity · original mouth-force cases · ideal all-peg clamp');save(fig,'mesh-sensitivity')
fig,ax=plt.subplots(figsize=(9,4.3));ax.plot([q['angle_deg'] for q in install['steps']],[q['front_host_intersection_mm3'] for q in install['steps']],label='Original assumed pivot',color='#ba5a3f',lw=2)
for q in candidates['candidates']:ax.plot([s['angle_deg'] for s in q['steps']],[s['front_host_intersection_mm3'] for s in q['steps']],label=f"Candidate outward relief {q['outward_clearance_at_25deg_mm']:g} mm")
ax.set_xlabel('Tilt from seated (degrees)');ax.set_ylabel('Front-host / board intersection (mm³)');ax.set_title('The old rear-peg swing screen omitted front-host material');ax.legend(frameon=False,fontsize=9);ax.grid(alpha=.15);save(fig,'installation-contact')
fig,axes=plt.subplots(1,2,figsize=(10,4.3))
for r,color in [(hoop4,'#97b59d'),(hoop,'#318d83')]:
 axes[0].plot([q['pinch_per_arm_mm'] for q in r['results']],[q['mean_force_per_arm_N'] for q in r['results']],'-o',label=f"h = {r['h_mm']:g} mm",color=color)
 axes[1].plot([q['pinch_per_arm_mm'] for q in r['results']],[q['von_mises_MPa']['max'] for q in r['results']],'-o',color=color)
axes[0].set_ylabel('Mean constrained-crest force per arm (N)');axes[1].set_ylabel('Peak linear von Mises stress (MPa)')
for ax in axes:ax.set_xlabel('Prescribed pinch per arm (mm)');ax.grid(alpha=.15)
axes[0].legend(frameon=False);fig.suptitle('Actual bottom hoop crop · fixed plate patch · not an insertion-force test');save(fig,'hoop-pinch')
# Independent beam estimate clarifies what the holder-only FEA leaves out.
loads=json.loads((R/'bench/source/key_fan_audit_v1/loads.json').read_text());tool_data=json.loads((R/'bench/source/three_set_rack_v1/key_sets.json').read_text());beam=[]
for q in loads['loads']:
 if q['set']!='tee':continue
 af=float(q['size']);length=float(np.linalg.norm(np.array(q['physical_grip_point_mm'])-q['point']));axis=(np.array(q['physical_grip_point_mm'])-q['point'])/length;force=np.array(q['force'],float);F=float(np.linalg.norm(force));parallel=float(np.dot(force,axis));perp2=F*F-parallel*parallel;area=math.sqrt(3)/2*af**2;I=5*math.sqrt(3)/144*af**4;E=210000.;along=perp2/F*length**3/(3*E*I)+parallel**2/F*length/(E*area);beam.append(dict(id=q['id'],nominal_free_length_mm=length,hex_I_mm4=I,assumed_steel_E_MPa=E,ideal_fixed_cantilever_deflection_along_force_mm=along))
(B/'beam-reference.json').write_text(json.dumps(dict(source_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),cases=beam,scope='Illustrative regular-hex, straight steel cantilever at the mouth, E=210 GPa assumed; not a Bondhus material measurement, contact model or assembled-rack rating'),indent=2)+'\n')
texts=[]
def section(title,body):texts.append('<section><h2>'+title+'</h2>'+body+'</section>')
section('What the extended checks changed','<div class="notice"><p><strong>The published v2 fan is a prototype baseline, not a physically qualified finished rack.</strong> Its owner-tested sockets did not provide the expected centering and rotation restraint; the revised 3/5 mm straight-guide coupons are separate fit trials.</p><p>The original stiffness numbers are reproducible for forces at the mouths, but they are not handle-tip load predictions. The same assumed installation pivot also brings front-host material into the board. No printed load rating follows from these results.</p></div>')
section('Exact geometry and traceability',f'<p>The audit uses the immutable installed STEP <code>{native["step_sha256"]}</code>. FreeCAD {".".join(native["freecad"][:3])}/OCC {native["occ"]} reports one valid solid, one shell and {native["native_faces"]:,} faces. Its native volume is {native["native_volume_mm3"]/1000:.3f} cm³. The released print STL is closed, has one component and differs in volume by {native["mesh_step_volume_error"]*100:.5f}%.</p><p>The rear extraction independently finds 90 pegs in ten rows of nine. Sources, hashes, native checks, solver receipts, display fields and film provenance accompany the downloadable review package. Original nominal anchor certificates remain separate from this changed-fit holder.</p>')
section('Loads: the missing lever arm','<p>The earlier five cases spread a force over nodes in a small spherical patch around each socket mouth. That is a legitimate numerical mouth-load screen. Its “lean on the handle” wording omitted the bending moment caused by applying that force at the handle.</p><p>The T10 model has about 183 mm from its mouth to grip centre. The new grip cases preserve the resultant force and the moment about the load-patch centroid, using a minimum-norm nodal force distribution. This is an equivalent wrench, not a modeled steel-tool/socket contact. Local peaks depend on how that patch is chosen.</p><p>Global force and moment balance are independently checked against the input deck and support reactions. Cases exceeding the acceptance threshold are excluded, rather than treated as plausible-looking solutions.</p><img src="mouth-versus-grip.png" alt="Maximum rack displacement under mouth-only and grip-moment loads" style="width:100%">')
section('Fixture sensitivity and the real mount','<p>The old “pegs” fixture fixes every node behind Y=0.10 mm—including loose bearing pegs and flexible locking material. It can carry tension and restraint those features may not supply physically. It is not generally a conservative model of a real pegboard.</p><p>The additional fixtures fix only the upper hook row, four corner regions, or the front/rear contact region. These are ideal sensitivity cases; they do not include hole clearance, unilateral contact, friction, compliant hardboard, wall attachment, crushing ribs or snap-arm motion.</p><img src="mount-sensitivity.png" alt="Rack displacement sensitivity to ideal mounting conditions" style="width:100%"><p>With the same 50 N T10 grip load, all-peg clamping gives about 0.091 mm maximum rack displacement; hooks-only gives about 4.27 mm. The weak fixture also produces stresses beyond the material-reference range, so its linear continuation is not a sustainable-load prediction. Four-corner restraint gives about 0.105 mm. This spread matters far more than choosing a slightly different solid modulus.</p>'+table(['Case','Fixture','Load application','Rack max mm','Work-equivalent load-point mm','Gauss peak MPa','Unweighted p99 MPa'],mount_table))
section('What displacement actually means','<p>Maximum rack displacement is the largest nodal displacement anywhere in the holder. The mouth-patch mean is a different quantity. For a grip wrench, work divided by force magnitude gives the work-conjugate displacement at the modeled external force point, including load-patch rotation. It can exceed the largest holder-node movement because the handle extends beyond the holder.</p><p>For T10 down 50 N, the all-peg grip case has about 0.091 mm maximum rack movement and 1.140 mm work-equivalent grip-direction movement. Do not compare the latter directly with the old 0.0062 mm mouth mean as if they were measured at the same point.</p><p>The tool itself is not meshed in the holder FEA. An illustrative regular-hex steel cantilever calculation, assuming E=210 GPa, adds about '+f'{beam[0]["ideal_fixed_cantilever_deflection_along_force_mm"]:.3f}'+' mm along the same T10 force direction. That is an assumption-based beam estimate, not a Bondhus material test or an assembled-rack measurement.</p>')
section('Mesh and numerical quality','<p>Gmsh 4.15.0 generates second-order C3D10 tetrahedra with linearly located midside nodes. Each accepted mesh is independently checked for positive corner-tetra determinants, one connected volume, native-volume agreement and poor-element quality statistics. Those checks do not establish stress convergence.</p>'+table(['Requested h mm','Nodes','Elements','Volume error'],mesh_table)+'<img src="mesh-sensitivity.png" alt="Displacement and peak stress variation with mesh refinement" style="width:100%">'+table(['Case','h7 max mm','h6 max mm','h5 max mm','Displacement spread','h7 peak MPa','h6 peak MPa','h5 peak MPa'],compare)+'<p>The maximum displacement changes by up to about 15% across these mouth-load meshes. Discrete load/support node selections also change. Sharp-edge and ideal-clamp stress maxima vary more strongly; no converged local failure stress or factor of safety is claimed.</p><p>Coarse h10 meshing produced overlapping facets; h3 refinement stalled or generated degenerate elements; a threaded h4 mesh crashed. A refined weak-mount multi-step solve failed the force-balance gate. Newer-solver and fresh-single-step cross-checks are documented separately. Failed runs are not silently included in the validated film dataset.</p>')
section('ASA, infill, layers and failure','<p>The reproduction model uses isotropic solid ASA, E=1800 MPa and Poisson ratio 0.35. It fills the entire CAD body with material. The actual 20% infill print, its two walls and locally solid braces do not have that homogeneous stiffness or stress distribution.</p><p>A reference orthotropic sensitivity uses build-normal E=1965 MPa and in-plane E=2379 MPa from the <a href="https://wiki.polymaker.com/polymaker-products/more-about-our-products/documents/technical-data-sheets/abs-asa/polymaker-tm-asa">manufacturer’s ASA data</a>. Installed X is the build-normal direction in the left-end print. Poisson ratios and shear constants in that scenario are assumed, not measured for this print.</p><p>The same source gives tensile reference values of 32 MPa across layers and 43.8 MPa in-plane. These are coupon results, not design allowables. Von Mises is a visualization scalar here, not an orthotropic fracture criterion. No layer-interface damage, creep, temperature-dependent behavior, impact, board flexibility or print defects are modeled.</p>')
section('Actual locking-hoop flexure','<p>The whole-rack fixture freezes much of the locking hardware behind the board; it cannot validate the snap. The separate study crops the actual centre bottom hoop with its plate/root patch, fixes the plate side, and prescribes 0.1–0.4 mm inward movement at each outer crest patch. It reports the constrained-crest reaction and stress under that ideal pinch.</p><img src="hoop-pinch.png" alt="Linear force and stress under prescribed hoop crest pinch" style="width:100%">'+table(['Pinch per arm mm','Total closure mm','Mean force per arm N','Peak linear MPa','Build-normal tension MPa'],[[q['pinch_per_arm_mm'],q['total_prescribed_closure_mm'],f"{q['mean_force_per_arm_N']:.2f}",f"{q['von_mises_MPa']['max']:.1f}",f"{q['build_normal_max_tension_MPa']:.1f}"] for q in hoop['results']])+'<p>The high predicted stresses mean this simple linear model does not establish a recoverable snap. Crest selection, root restraint and contact path matter. These reactions are not insertion forces: the study has no board contact, friction, plastic deformation, damage or actual loading/unloading test. The animated motion is amplified and returns only because the mathematical model is elastic.</p>')
section('All 26 tool paths','<p>The finer native screen samples 13 rigid straightening poses and 1 mm withdrawal translations for every tool, retaining the original other tools and shelf as obstacles. All 26 pass those sampled poses, '+str(sum(q['sample_count'] for q in motion['tools']))+' poses in total. Rigid cloud fitting error stays below '+f'{max(q["rigid_fit_max_error_mm"] for q in motion["tools"]):.2e}'+' mm.</p><p>The original straightening check interpolated tool points, which can shorten a rotating proxy. This audit uses rigid rotations with a linearly interpolated tip. Neither version is a continuous certificate or a gravity/contact simulation. The returned tool reverses the prescribed screened path; a natural one-handed drop-in is not proven.</p><p>Catalogue dimensions and assumed grip/short-arm envelopes remain proxies. The original v2 clocking is corner-based; the owner has confirmed flat-to-flat for the revised fit. These old-rack path checks must be repeated after adopting new guides, clearances or grip orientations.</p>')
section('Installation: front-host collision and candidate paths',f'<p>The original sampled swing checks the bearing and locking pegs around an assumed fixed pivot, reporting nominal seated clearance and permitted small grazing volumes. It did not test all front-host material.</p><p>On the same pivot, the front host intersects the nominal board by <strong>{install["worst_front_host_intersection_mm3"]:.2f} mm³ at {install["worst_front_host_angle_deg"]:.1f}°</strong>. It is clear when seated. This disproves full clearance for that assumed rigid trajectory, not the possibility of installing by another real path.</p><img src="installation-contact.png" alt="Front-host board overlap on original and translated candidate swing paths" style="width:100%"><p>Adding outward translation proportional to sin(angle) clears the front host at the tested 0.5° samples for 1.5 and 2.0 mm relief at 25°. Those are candidates, not recommendations or qualified installation paths: hook engagement, rear-peg intersections, compliance and continuous motion still need examination. The viewer shows the original collision in red and allows comparison with the 1.5 mm candidate.</p>')
section('Ninety pegs make tolerance accumulation important','<p>The nominal bearing array is clear when seated on the nominal holes. The sensitivity study varies hole diameter, pitch and uniform residual part scale. The ranges are illustrative, not measured board tolerances. It examines bearing intersections, not clamp force or hoop recoverability.</p>'+table(['Board mm','Hole diameter mm','Pitch mm','Residual scale','Bearing pegs intersecting','Max overlap per peg mm³'],[[q['board_thickness_mm'],q['hole_diameter_mm'],q['pitch_mm'],q['residual_part_scale'],q['bearing_pegs_with_intersection_gt_1e_4'],f"{q['max_seated_bearing_intersection_mm3']:.3f}"] for q in install['seated_bearing_sensitivities']])+'<p>Even ±0.1% uniform residual scale creates measurable intersection at many bearings. A 0.54% scale error changes a 228.6 mm grid span by about 1.24 mm. Overlap volume does not tell you maximum penetration or the force needed to seat it.</p>')
section('Print preparation and the brace project','<p>The bare print mesh is 252.576 × 92.405 × 236 mm. The earlier downloadable brace project already enlarged all geometry by about 1.00543, so its body spans 253.948 × 92.907 × 237.281 mm. A complete 5 mm brim around that straight footprint needs 263.948 mm in its long direction—beyond a 256 mm bed.</p><p>A 45° rotation within the bed plane gives a bounding square of about 245.26 mm for that compensated body; adding 5 mm each side leaves only about 0.37 mm per side. Tree-support reach, actual excluded areas and compensation must be checked in the real toolpaths. An in-plane rotation preserves shaft elevation and hex-flat orientation relative to the layers.</p><p>The historical project’s pre-baked compensation can be applied again when opened with a normal calibrated filament profile. The new geometry-only project uses the exact unscaled body and braces in their original relative positions, with the brace modifier at 100%. It embeds no printer/filament profile or G-code. Apply your actual compensation once and reslice.</p><p>The recorded plain review slice was 554 g / 25.7 h; braces 636 g / 30.4 h, with about 85–88 g of support. Those are historical review estimates. Raw overhang and island gates were false, with four island declarations and slicer supports—not a blanket support-free or all-gates-pass qualification.</p>')
section('Fit trial and physical evidence','<p>The owner’s original coupon allowed roughly 15° of small-key rocking and full rotation in both 5 mm tests. The v6 trials use true six-flat 40 mm guides, a separate 0.8 mm entrance, square 3 mm floors and 1 mm vents. Only the actual 3 and 5 mm test sizes are requested; no 7 mm trial is included in the print job.</p><p>A–E total AF allowances are 0.20 / 0.30 / 0.38 / 0.46 / 0.56 mm; C matches the latest requested clearance. Longer guidance does not erase rotational clearance: 3E can turn fully in ideal geometry. The owner must choose letters from actual seating, extraction, rocking and rotation after printing.</p><p>The supported Orca job was validated for the reported P1S 0.4 nozzle and physical AMS slot 3. It paused before the first layer on an AMS feed failure, so no new physical fit result or winning letters are claimed. Printer credentials, camera images, private presets and machine-specific G-code are excluded from the publication.</p>')
section('How to read the films','<p>Cel-shaded motion clips use the exact released holder with reference tool proxies. FEA deformation comes from solver nodal displacements, not an invented bend. The numeric magnification is stated in-frame. Stress colors represent adjacent-element averages on boundary nodes and saturate at the stated legend limit; numerical peak statistics use original integration-point stresses.</p><p>Display fields are quantized with explicitly bounded errors; the numerical report remains full precision. Load ramps scale static linear solutions. They are not natural vibration, impact, time integration, fracture or proof of elastic recovery. Red installation highlights are geometric contact on the modeled board, not simulated plastic deformation.</p>')
section('What remains before calling the rack qualified','<ol><li>Finish the physical 3/5 mm fit spectrum and select actual letters; adopt the chosen guide/bore/floor/vent geometry in a full rack.</li><li>Recheck loaded layout, tool removal and whole-host installation after that geometry change. Measure the actual install trajectory and board rather than relying on the assumed pivot.</li><li>Print a mounting/locking coupon and measure seating force, hoop recovery and real grid fit. Use those measurements to calibrate contact/support assumptions.</li><li>Verify compensation once, complete brim/support fit, clean internal guide roofs and support release in the actual owner-profile toolpaths.</li><li>Model or measure the printed wall/brace/infill structure and elastic board; use realistic tool/socket contact for local stress. Verify nonlinear and layer failure behavior before assigning a load rating.</li></ol>')
# Late independent refined fixtures; rejected weak results remain excluded.
refined=[]
for name in ['fea-h5-face.json','fea-h5-four-corners.json']:
 r=load(name);old=next(q for q in mounts if q['support']==r['support'] and q['force_mode']=='grip-wrench')
 for q,baseline in zip(r['loads'],old['loads']):
  assert q['force_balance_relative_error']<.01
  refined.append([r['support'],q['id'],f"{baseline['max_deflection_mm']:.5f}",f"{q['max_deflection_mm']:.5f}",f"{100*(q['max_deflection_mm']/baseline['max_deflection_mm']-1):+.1f}%",f"{q['force_balance_relative_error']:.2e}"])
section('Independent refined grip fixtures', '<p>Fresh h = 5 mm runs complete all five grip-wrench loads for the rigid face and four-corner fixtures. All force-balance gates pass. The largest displacement difference from h = 7 mm is 16.0% for the face-clamped Hex10 downward case; this reinforces mesh sensitivity rather than establishing convergence. The viewer and films retain their labeled h = 7 mm fields.</p>'+table(['Fixture','Load','h7 rack max mm','h5 rack max mm','Change','Relative force residual'],refined)+'<p>The independent h7 force-and-moment audit also passes. Fresh single-step reruns recover the h7 sideways hook and 1.5× patch T50 outward cases; a fresh h5 downward hook case still fails. Rejected multi-step weak-fixture runs and the bundled solver crash remain excluded.</p>')
section('References','<p><a href="https://www.dhondt.de/ccx_2.21.pdf">CalculiX 2.21 manual</a> defines the node reaction and integration-point stress output used here. <a href="https://gmsh.info/doc/texinfo/gmsh.html">Gmsh documentation</a> describes second-order meshing and linearly placed midside nodes. <a href="https://3989ac5bcbe1edfc864a-0a7f10f87519dba22d2dbc6233a731e5.ssl.cf2.rackcdn.com/bondhus42/catalogs/2023/2023_US_Bondhus_Catalog_A.pdf">Bondhus 2023 catalogue, printed pages 37–38</a> matches the fan’s graduated 133xx metric T-handle lengths and grip widths; these differ from the separate HX05 131xx ball-end sets. Grip thickness remains an assumption. <a href="https://wiki.polymaker.com/polymaker-products/more-about-our-products/documents/technical-data-sheets/abs-asa/polymaker-tm-asa">Polymaker ASA technical data</a> supplies the reference directional moduli/strength values, not measurements of this particular print.</p>')
body=''.join(texts);page='<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HX04 · Full engineering audit</title><link rel="stylesheet" href="study.css"></head><body><header><a href="./">← Interactive studies and films</a><p class="eyebrow">HX04 · methods and evidence</p><h1>The fan rack under scrutiny.</h1><p>Reproduction, stronger tests, useful failures and the limits of idealized simulation.</p></header><main>'+body+'</main></body></html>'
(D/'report.html').write_text(page,encoding='utf-8',newline='\n')
headline='Grip moments, mounting assumptions and whole-host installation change the conclusions. The prototype fit remains unqualified.'
summary='<div class="notice"><p>The old mouth-force numbers reproduce, but do not include the handle lever arm. The assumed swing also intersects the front host. The owner’s original fit print failed expectations.</p></div>'+table(['T10 down 50 N','Rack max mm','Work-equivalent grip mm'],[[q['support'],f"{q['loads'][0]['max_deflection_mm']:.4f}",f"{q['loads'][0]['work_equivalent_deflection_mm']:.4f}"] for q in mounts[1:]])+'<p>All 26 tools pass finer sampled removal paths. No physical load or snap rating is established. Open the full report for mesh, material, hoop, grid and print-preparation details.</p>'
(D/'results.json').write_text(json.dumps(dict(headline=headline,summary_html=summary,native=native,mount_sensitivity=h7,mesh_h6=h6,mesh_h5=h5,orthotropic_reference=ortho,patch_2x=patch2,motion=motion,installation=install,installation_candidates=candidates,hoop=hoop,project=project),indent=2)+'\n')
(B/'REPORT.md').write_text('# HX04 extended engineering audit\n\n'+headline+'\n\nThe authored full report is [report.html](../../../docs/gallery/key-fan/studies/report.html); the interactive study uses exact source and field hashes in scene.json.\n\n'+ '\n\n'.join('## '+re.split(r'</h2>',q,1)[0].split('<h2>')[1] for q in texts)+'\n') if False else None
(B/'report-build.json').write_text(json.dumps(dict(source_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),report_sha256=hashlib.sha256((D/'report.html').read_bytes()).hexdigest(),results_sha256=hashlib.sha256((D/'results.json').read_bytes()).hexdigest(),scope='Authored audit of immutable published v2 geometry; no physical qualification'),indent=2)+'\n')
print('Built complete numerical report, tables and five scientific plots')
