const fs=require('fs'),path=require('path'),crypto=require('crypto'),{spawnSync}=require('child_process');
const root=process.env.HX04_ROOT||'/mnt/keith/bench/hx04-fan-audit-e487d4c', {chromium}=require(process.env.PLAYWRIGHT_MODULE||root+'/viewer/node_modules/playwright-core');
const worker=+(process.argv[2]||0),workers=+(process.argv[3]||1),frames=+(process.env.FRAMES||96),fps=12;
const sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
(async()=>{const data=JSON.parse(fs.readFileSync(root+'/viewer-data/scene.json'));const jobs=[];
for(const q of data.tools)jobs.push({id:`motion-${q.set}-${q.size}`,mode:'motion',tool:q.index,title:`${q.set==='tee'?'T-handle':q.set==='hex'?'Hex L-key':'Torx'} ${q.size} removal and return`,caption:`Rigid prescribed path; ${q.sample_count} sampled poses at 1 mm withdrawal steps.`,source:q.mesh});
for(let i=0;i<data.fields.length;i++){const q=data.fields[i];jobs.push({id:`stress-${q.support}-${q.force_mode}-${i%5+1}`,mode:'fea',field:i,shade:'stress',title:`${q.id} · ${q.support}`,caption:`${q.force_mode}, solid ASA. Deformation magnification stated in-frame; static load ramp, not dynamics.`,source:q.file});}
for(const field of [5,8,10,15,20]){const q=data.fields[field];jobs.push({id:`flexure-cel-${q.support}-${field%5+1}`,mode:'fea',field,shade:'cel',title:`Cel-shaded flexure · ${q.id} · ${q.support}`,caption:'Actual computed deformation, amplified for visibility; no infill or elastic board model.',source:q.file});}
jobs.push({id:'install-full-host',mode:'install',title:'Full-host installation path',caption:'Rigid rotation around the published assumed pivot. Red marks front-host material within the reference board; this path is not fully clear.',source:'install-audit.json'});
fs.mkdirSync(root+'/films',{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome',args:['--no-sandbox','--disable-dev-shm-usage','--use-angle=swiftshader','--enable-unsafe-swiftshader']});const page=await browser.newPage({viewport:{width:1400,height:950},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});await page.goto('http://127.0.0.1:39881/');await page.waitForFunction(()=>window.studyReady&&window.setView,{timeout:60000});await page.evaluate(()=>window.studyReady);
for(let index=worker;index<jobs.length;index+=workers){const job=jobs[index],dir=root+'/films/'+job.id;if(fs.existsSync(dir+'/receipt.json')){console.log('SKIP completed',job.id);continue}const start=Date.now();fs.mkdirSync(dir,{recursive:true});await page.evaluate(q=>window.setStudy(q),job);const view=job.mode==='fea'?{position:[.30,.035,.48],target:[0,-.20,.04]}:{position:[.43,.18,.72],target:[0,-.13,.05]};await page.evaluate(q=>window.setView(q),view);await page.waitForTimeout(150);const state=await page.evaluate(()=>window.studyState());job.amplification=job.mode==='fea'?state.scale:1;
for(let frame=0;frame<frames;frame++){const p=.5-.5*Math.cos(frame/frames*2*Math.PI);await page.evaluate(p=>window.renderAt(p),p);await page.locator('#stage').screenshot({path:dir+'/'+String(frame).padStart(4,'0')+'.png'});}
let r=spawnSync('ffmpeg',['-y','-v','error','-threads','2','-framerate',String(fps),'-i',dir+'/%04d.png','-c:v','libvpx-vp9','-crf','30','-b:v','0','-row-mt','1','-pix_fmt','yuv420p','-threads','2',dir+'/'+job.id+'.webm'],{encoding:'utf8',timeout:120000});if(r.status)throw Error(r.stderr||`webm exit ${r.status}`);
r=spawnSync('ffmpeg',['-y','-v','error','-framerate',String(fps),'-i',dir+'/%04d.png','-filter_complex','fps=12,scale=900:-2:flags=lanczos,split[s0][s1];[s0]palettegen=max_colors=128:stats_mode=diff[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3','-loop','0',dir+'/'+job.id+'.gif'],{encoding:'utf8',timeout:120000});if(r.status)throw Error(r.stderr||`gif exit ${r.status}`);
fs.copyFileSync(dir+'/'+String(Math.round(frames/2)).padStart(4,'0')+'.png',dir+'/poster.png');const receipt={...job,frames,fps,seconds:(Date.now()-start)/1000,source_scene_sha256:sha(root+'/viewer-data/scene.json'),recorder_sha256:sha(__filename),viewer_js_sha256:sha(root+'/viewer-site/study.js'),camera:view,files:Object.fromEntries([job.id+'.webm',job.id+'.gif','poster.png'].map(name=>[name,{sha256:sha(dir+'/'+name),bytes:fs.statSync(dir+'/'+name).size}]))};fs.writeFileSync(dir+'/receipt.json',JSON.stringify(receipt,null,2)+'\n');for(let frame=0;frame<frames;frame++)fs.unlinkSync(dir+'/'+String(frame).padStart(4,'0')+'.png');console.log('COMPLETE',job.id,receipt.seconds.toFixed(1),'s',receipt.files[job.id+'.webm'].bytes,receipt.files[job.id+'.gif'].bytes);if(errors.length)throw Error(errors.join('\n'));}
await browser.close();console.log('WORKER COMPLETE',worker);})().catch(e=>{console.error(e);process.exit(1)});
