import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id),canvas=$('canvas');
const scene=new THREE.Scene();scene.background=new THREE.Color('#f2efe6');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const camera=new THREE.PerspectiveCamera(38,1,.005,6),orbit=new OrbitControls(camera,canvas);orbit.enableDamping=true;orbit.minDistance=.18;orbit.maxDistance=1.8;
scene.add(new THREE.AmbientLight(0xffffff,1.1));const key=new THREE.DirectionalLight(0xffffff,2);key.position.set(-.5,.8,.8);scene.add(key);const fill=new THREE.DirectionalLight(0xffffff,.5);fill.position.set(.6,.2,.3);scene.add(fill);
const bands=new THREE.DataTexture(new Uint8Array([100,100,100,255,155,155,155,255,215,215,215,255,255,255,255,255]),4,1,THREE.RGBAFormat);bands.minFilter=bands.magFilter=THREE.NearestFilter;bands.needsUpdate=true;
const root=new THREE.Group(),rack=new THREE.Group(),toolRoot=new THREE.Group(),femRoot=new THREE.Group(),ghostRoot=new THREE.Group(),boardRoot=new THREE.Group();scene.add(root);root.add(rack,toolRoot,femRoot,ghostRoot,boardRoot);
const ground=new THREE.Mesh(new THREE.PlaneGeometry(1.4,1.4),new THREE.MeshBasicMaterial({color:'#e7e4da'}));ground.rotation.x=-Math.PI/2;ground.position.y=-.39;scene.add(ground);
const grid=new THREE.GridHelper(1.2,24,0xd4d5ca,0xe0e0d5);grid.position.y=-.389;scene.add(grid);
const state={mode:'motion',tool:20,field:5,phase:0,play:true,scale:100,shade:'stress',cycle:8},meshes=new Map(),fieldCache=new Map();let data,toolObjects=[],fem,undeformed,arrow,fieldUniforms=[],edges;let installUniforms;
const T=new THREE.Matrix3().set(-1,0,0,0,0,1,0,1,0);
function xyz(v){return new THREE.Vector3(-v[0]*.001,v[2]*.001,v[1]*.001)}
function resize(){const b=canvas.getBoundingClientRect();renderer.setSize(b.width,b.height,false);camera.aspect=b.width/b.height;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe($('stage'));
function reset(){camera.position.set(.41,.17,.64);orbit.target.set(0,-.14,.045);orbit.update()};reset();
async function bytes(file){const r=await fetch('data/'+file);if(!r.ok)throw Error(`${file}: ${r.status}`);return r.arrayBuffer()}
async function geometry(desc){if(meshes.has(desc.file))return meshes.get(desc.file);const b=await bytes(desc.file),g=new THREE.BufferGeometry(),v=new Float32Array(b,0,desc.vertices*6),p=new Float32Array(desc.vertices*3),n=new Float32Array(p.length);for(let i=0;i<desc.vertices;i++){p.set(v.subarray(i*6,i*6+3),i*3);n.set(v.subarray(i*6+3,i*6+6),i*3)}g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('normal',new THREE.BufferAttribute(n,3));g.setIndex(new THREE.BufferAttribute(new Uint32Array(b,desc.vertices*24,desc.indices),1));g.computeBoundingSphere();meshes.set(desc.file,g);return g}
function inkObject(g,color){const group=new THREE.Group(),mat=new THREE.MeshToonMaterial({color,gradientMap:bands}),body=new THREE.Mesh(g,mat);group.add(body);const silhouette=new THREE.MeshBasicMaterial({color:0x111c1a,side:THREE.BackSide});silhouette.onBeforeCompile=s=>{s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','vec3 transformed = vec3(position) + normal * 0.00065;')};const outline=new THREE.Mesh(g,silhouette);outline.renderOrder=-1;group.add(outline);const lines=new THREE.LineSegments(new THREE.EdgesGeometry(g,22),new THREE.LineBasicMaterial({color:0x17241f,transparent:true,opacity:.65}));group.add(lines);return group}
function installMaterial(mat){const q=data.install,lo=q.body_bbox_mm[0],hi=q.body_bbox_mm[1],u={installActive:{value:0},top:{value:q.hole_top_row_z_mm*.001},lower:{value:new THREE.Vector3(-(hi[0]+30)*.001,(lo[2]-60)*.001,(q.board_front_mm-q.board_thickness_mm)*.001)},upper:{value:new THREE.Vector3(-(lo[0]-30)*.001,(hi[2]+20)*.001,q.board_front_mm*.001)}};installUniforms=u;mat.onBeforeCompile=s=>{Object.assign(s.uniforms,u);s.vertexShader='varying vec3 vStudyWorld; varying float vOriginalZ;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>','#include <begin_vertex>\nvOriginalZ=position.z;vStudyWorld=(modelMatrix*vec4(transformed,1.)).xyz;');s.fragmentShader='uniform float installActive;uniform float top;uniform vec3 lower;uniform vec3 upper;varying vec3 vStudyWorld;varying float vOriginalZ;\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nif(installActive>.5&&vOriginalZ>=.00015&&all(greaterThanEqual(vStudyWorld,lower))&&all(lessThanEqual(vStudyWorld,upper))){vec2 c=vec2(round(vStudyWorld.x/.0254)*.0254,top-round((top-vStudyWorld.y)/.0254)*.0254);if(distance(vStudyWorld.xy,c)>.003175)diffuseColor.rgb=vec3(.75,.055,.028);}');};mat.customProgramCacheKey=()=>"hx04-install-contact";}
async function makeBoard(){if(data.board){const g=await geometry(data.board),m=new THREE.Mesh(g,new THREE.MeshToonMaterial({color:'#c7b18d',gradientMap:bands,transparent:true,opacity:.45,depthWrite:false}));boardRoot.add(m);boardRoot.add(new THREE.LineSegments(new THREE.EdgesGeometry(g,25),new THREE.LineBasicMaterial({color:'#6a6552',transparent:true,opacity:.26,depthWrite:false})));return}const params=data.install||{hole_top_row_z_mm:-94.97,pivot_installed_mm:[0,-1.82,-91.8]},top=params.hole_top_row_z_mm*.001,pitch=.0254;const sh=new THREE.Shape();sh.moveTo(-.15,-.36);sh.lineTo(.15,-.36);sh.lineTo(.15,-.04);sh.lineTo(-.15,-.04);sh.closePath();for(let col=-5;col<=5;col++)for(let row=-1;row<=10;row++){const hole=new THREE.Path();hole.absarc(col*pitch,top-row*pitch,.003175,0,Math.PI*2,true);sh.holes.push(hole)}const g=new THREE.ExtrudeGeometry(sh,{depth:.00394,bevelEnabled:false,curveSegments:16});g.translate(0,0,-.00379);const m=new THREE.Mesh(g,new THREE.MeshToonMaterial({color:'#c7b18d',gradientMap:bands,transparent:true,opacity:.45,depthWrite:false}));boardRoot.add(m);const e=new THREE.LineSegments(new THREE.EdgesGeometry(g,25),new THREE.LineBasicMaterial({color:'#6a6552',transparent:true,opacity:.26,depthWrite:false}));boardRoot.add(e);const shelf=new THREE.Mesh(new THREE.BoxGeometry(.6,.004,.1262),new THREE.MeshBasicMaterial({color:'#8d9d94',transparent:true,opacity:.14,depthWrite:false}));shelf.position.set(0,.10012,.0131);boardRoot.add(shelf)}
function toolTransform(q,f,translation){const R0=new THREE.Matrix4().set(...q.rest_rotation[0],0,...q.rest_rotation[1],0,...q.rest_rotation[2],0,0,0,0,1),quat0=new THREE.Quaternion().setFromRotationMatrix(R0),quat=quat0.clone().slerp(new THREE.Quaternion(),f),R=new THREE.Matrix3().setFromMatrix4(new THREE.Matrix4().makeRotationFromQuaternion(quat)),up=new THREE.Vector3(...q.tip_up_mm),anchor=new THREE.Vector3(...q.tip_rest_mm).lerp(up,f),offset=anchor.sub(up.clone().applyMatrix3(R)).add(new THREE.Vector3(...translation));const world=T.clone().multiply(R).multiply(T.clone().transpose()),a=world.elements;return new THREE.Matrix4().set(a[0],a[3],a[6],-offset.x*.001,a[1],a[4],a[7],offset.z*.001,a[2],a[5],a[8],offset.y*.001,0,0,0,1)}
function motionPose(q,p){let f=0,move=[0,0,0];if(p<.2)f=p/.2;else if(p<.55){f=1;move=q.lift_vector_mm.map(v=>v*(p-.2)/.35)}else{f=1;move=q.lift_vector_mm.map((v,i)=>v+q.escape_vector_mm[i]*(p-.55)/.45)}return toolTransform(q,f,move)}
const mapGLSL=`vec3 studyMap(float x){x=clamp(x,0.,1.);vec3 a=vec3(.106,.137,.376),b=vec3(.125,.467,.710),c=vec3(.125,.722,.667),d=vec3(.647,.863,.271),e=vec3(.945,.812,.224),f=vec3(.937,.439,.161),g=vec3(.710,.137,.145);vec3 rgb=x<.16?mix(a,b,x/.16):x<.33?mix(b,c,(x-.16)/.17):x<.5?mix(c,d,(x-.33)/.17):x<.66?mix(d,e,(x-.5)/.16):x<.82?mix(e,f,(x-.66)/.16):mix(f,g,(x-.82)/.18);return pow(rgb,vec3(2.2));}`;
function fieldMaterial(base,outline=false){const uniforms={phase:{value:0},amplification:{value:100},colorLimit:{value:1},display:{value:0}};base.onBeforeCompile=s=>{Object.assign(s.uniforms,uniforms);s.vertexShader='attribute vec3 studyDisplacement; attribute float studyStress; uniform float phase; uniform float amplification; varying float vStudyStress; varying float vStudyDisplacement;\n'+s.vertexShader;s.vertexShader=s.vertexShader.replace('#include <begin_vertex>',`vec3 transformed=vec3(position)+studyDisplacement*phase*amplification${outline?'+normal*0.00065':''};vStudyStress=studyStress*phase;vStudyDisplacement=length(studyDisplacement)*phase*1000.;`);if(!outline){s.fragmentShader='uniform float colorLimit; uniform float display; varying float vStudyStress; varying float vStudyDisplacement;\n'+mapGLSL+'\n'+s.fragmentShader;s.fragmentShader=s.fragmentShader.replace('#include <color_fragment>','#include <color_fragment>\nif(display<1.5)diffuseColor.rgb=studyMap((display<.5?vStudyStress:vStudyDisplacement)/max(colorLimit,0.0000001));')}};base.customProgramCacheKey=()=>`hx04-field-${outline?'outline':'fill'}-${base.type}`;fieldUniforms.push(uniforms);return base}
async function loadField(index){const q=data.fields[index];$('loading').hidden=false;let values=fieldCache.get(q.file);if(!values){const b=await bytes(q.file),raw=(new Uint8Array(b)[0]===31&&new Uint8Array(b)[1]===139)?await new Response(new Blob([b]).stream().pipeThrough(new DecompressionStream('gzip'))).arrayBuffer():b,a=new Int16Array(raw),u=new Uint16Array(raw),D=new Float32Array(q.vertices*3),S=new Float32Array(q.vertices);for(let i=0;i<q.vertices;i++){for(let k=0;k<3;k++)D[i*3+k]=a[i*4+k]*q.displacement_quant_step_m[k];S[i]=u[i*4+3]*q.stress_quant_step_MPa}values={D,S};fieldCache.set(q.file,values)}const g=(await geometry(data.fem)).clone();g.setAttribute('studyDisplacement',new THREE.BufferAttribute(values.D,3));g.setAttribute('studyStress',new THREE.BufferAttribute(values.S,1));g.boundingSphere.radius+=.05;femRoot.clear();fieldUniforms=[];const material=state.shade==='cel'?new THREE.MeshToonMaterial({color:'#44978f',gradientMap:bands}):new THREE.MeshBasicMaterial({color:0xffffff});fem=new THREE.Mesh(g,fieldMaterial(material));fem.frustumCulled=false;femRoot.add(fem);const outline=new THREE.Mesh(g,fieldMaterial(new THREE.MeshBasicMaterial({color:'#101a17',side:THREE.BackSide}),true));outline.frustumCulled=false;femRoot.add(outline);ghostRoot.clear();const ghostGeo=await geometry(data.fem);undeformed=new THREE.LineSegments(new THREE.EdgesGeometry(ghostGeo,28),new THREE.LineBasicMaterial({color:'#42534b',transparent:true,opacity:.16,depthWrite:false}));ghostRoot.add(undeformed);state.field=index;state.scale=Math.max(1,Math.round(q.default_exaggeration));$('scale').value=state.scale;if(arrow)scene.remove(arrow);const direction=xyz(q.force_N).normalize(),point=xyz(q.force_point_mm);arrow=new THREE.ArrowHelper(direction,point,.047,0xb55235,.012,.006);scene.add(arrow);$('loading').hidden=true;update()}
function update(){if(!data)return;const mode=state.mode;if(installUniforms)installUniforms.installActive.value=mode==='install'?1:0;toolRoot.visible=mode==='motion';rack.visible=mode!=='fea';femRoot.visible=mode==='fea';ghostRoot.visible=mode==='fea'&&$('ghost').checked;boardRoot.visible=$('board').checked;arrow&&(arrow.visible=mode==='fea');$('toolLabel').hidden=mode!=='motion';$('caseLabel').hidden=mode!=='fea';$('shadeLabel').hidden=mode!=='fea';$('scaleLabel').hidden=mode!=='fea';$('legend').hidden=mode!=='fea'||state.shade==='cel';rack.position.set(0,0,0);rack.quaternion.identity();
 if(mode==='motion'){for(let i=0;i<toolObjects.length;i++){const q=data.tools[i],m=motionPose(q,i===state.tool?state.phase:0);toolObjects[i].matrix.copy(m);toolObjects[i].matrixWorldNeedsUpdate=true}const q=data.tools[state.tool];$('caption').textContent=`${q.set==='tee'?'T-handle':q.set==='hex'?'Hex L-key':'Torx L-key'} ${q.size} · removal / return`;$('detail').textContent=`${state.phase<.2?'Straightening as a rigid tool':state.phase<.55?'Lifting from the seat':'Leaving on the screened route'} · ${q.sample_count} sampled poses · ${q.passed?'sampled clear':'intersection found'}`;$('scope').textContent='Prescribed rigid straightening and reverse return path. Other tools remain at rest. 1 mm withdrawal sampling is not a continuous proof; tool dimensions and physical fit still need verification.'}
 if(mode==='fea'){const q=data.fields[state.field],limit=state.shade==='displacement'?q.max_deflection_mm:Math.max(.1,q.von_mises_MPa.p99*2);for(const u of fieldUniforms){u.phase.value=state.phase;u.amplification.value=state.scale;u.colorLimit.value=limit;u.display.value=state.shade==='stress'?0:state.shade==='displacement'?1:2}$('caption').textContent=`${q.id} · ${q.support.replaceAll('-',' ')}`;$('detail').textContent=`${q.force_mode==='mouth'?'Mouth force only':'Grip force + equivalent moment'} · ${(Math.hypot(...q.force_N)*state.phase).toFixed(1)} N · rack max ${(q.max_deflection_mm*state.phase).toFixed(4)} mm · shown ${state.scale}×`;$('legendTitle').textContent=state.shade==='displacement'?'Displacement · mm':'Averaged boundary stress · MPa';$('legendMax').textContent=limit.toPrecision(3)+(state.shade==='stress'?'+':'');$('scope').textContent='Solid ASA, ideal clamps; no elastic board, infill, layer interfaces or tool contact. Static linear load ramp, not transient dynamics. Stress colors clip at the legend maximum; reported integration-point peak is '+q.von_mises_MPa.max.toFixed(2)+' MPa. Amplification applies only to displayed deformation.'}
 if(mode==='install'){const q=data.install||{},p=xyz(q.pivot_installed_mm||[0,-1.82,-91.8]),angle=(1-state.phase)*25*Math.PI/180;rack.position.copy(p);rack.rotation.x=-angle;const shift=p.clone().applyAxisAngle(new THREE.Vector3(1,0,0),-angle).negate();rack.position.add(shift);$('caption').textContent='Empty rack · assumed installation pivot';$('detail').textContent=`${((1-state.phase)*25).toFixed(1)}° from seated · front-host overlap ${data.install.steps.reduce((best,s)=>Math.abs(s.angle_deg-(1-state.phase)*25)<Math.abs(best.angle_deg-(1-state.phase)*25)?s:best).front_host_intersection_mm3.toFixed(1)} mm³ on this assumed path`;$('scope').textContent='The fixed pivot is an assumption. Rear-peg grazing, intentional snap overlap and front-host contact are separate geometric checks; these do not predict insertion force or a recoverable snap.'}
 $('phase').value=state.phase;renderer.render(scene,camera)}
$('study').addEventListener('change',async()=>{state.mode=$('study').value;if(state.mode==='fea')await loadField(state.field);update()});$('tool').addEventListener('change',()=>{state.tool=+$('tool').value;update()});$('case').addEventListener('change',()=>loadField(+$('case').value));$('shade').addEventListener('change',async()=>{state.shade=$('shade').value;await loadField(state.field)});$('scale').addEventListener('input',()=>{state.scale=Math.max(1,Math.min(1000,+$('scale').value||1));update()});$('phase').addEventListener('input',()=>{state.play=false;$('play').textContent='Play';state.phase=+$('phase').value;update()});$('play').addEventListener('click',()=>{state.play=!state.play;$('play').textContent=state.play?'Pause':'Play'});$('reset').onclick=reset;$('board').onchange=$('ghost').onchange=update;
let last=performance.now(),clock=0;function tick(now){const dt=(now-last)/1000;last=now;if(state.play){clock+=dt;state.phase=.5-.5*Math.cos(clock*Math.PI*2/state.cycle)}const cameraChanged=orbit.update();if(state.play||cameraChanged)update();requestAnimationFrame(tick)}
window.studyReady=(async()=>{const response=await fetch('data/scene.json');if(!response.ok)throw Error('Scene data unavailable');data=await response.json();const rackObject=inkObject(await geometry(data.holder),'#44978f');rack.add(rackObject);installMaterial(rackObject.children[0].material);for(const q of data.tools){const group=inkObject(await geometry(q.display_mesh),q.set==='tee'?'#d9954b':q.set==='torx'?'#9aabc0':'#bac6c9');group.matrixAutoUpdate=false;toolRoot.add(group);toolObjects.push(group);const o=document.createElement('option');o.value=q.index;o.textContent=`${q.set==='tee'?'T-handle':q.set==='hex'?'Hex L-key':'Torx'} ${q.size}`;$('tool').append(o)}$('tool').value=state.tool;for(let i=0;i<data.fields.length;i++){const q=data.fields[i],o=document.createElement('option');o.value=i;o.textContent=`${q.id} · ${q.support} · ${q.force_mode}`;$('case').append(o)}$('case').value=state.field;await makeBoard();$('loading').hidden=true;resize();update();requestAnimationFrame(tick);try{const r=await fetch('results.json');if(r.ok){const info=await r.json();$('summary').textContent=info.headline||'Published fan geometry, audited with explicit loads and assumptions.';$('resultsBody').innerHTML=info.summary_html||''}}catch{}try{const r=await fetch('films.json');if(r.ok){const films=await r.json();for(const f of films){const article=document.createElement('article');article.className='film';const video=document.createElement('video');video.src=f.video;video.poster=f.poster||'';video.controls=true;video.loop=true;video.muted=true;video.playsInline=true;video.preload='none';const h=document.createElement('h3');h.textContent=f.title;const p=document.createElement('p');p.textContent=f.caption;const link=document.createElement('a');link.href=f.gif;link.textContent='Download GIF';p.append(document.createElement('br'),link);article.append(video,h,p);$('films').append(article)}}}catch{}return data})();
window.setStudy=async options=>{await window.studyReady;state.play=false;$('play').textContent='Play';if(options.mode){state.mode=options.mode;$('study').value=options.mode}if(options.tool!==undefined){state.tool=options.tool;$('tool').value=options.tool}if(options.shade){state.shade=options.shade;$('shade').value=options.shade}if(state.mode==='fea')await loadField(options.field??state.field);if(options.scale!==undefined){state.scale=options.scale;$('scale').value=options.scale}if(options.phase!==undefined)state.phase=options.phase;update();return true};window.renderAt=phase=>{state.play=false;state.phase=phase;update();return true};window.studyState=()=>({...state});window.studyReady.catch(error=>{$('loading').textContent=error.message;console.error(error)});

window.setView=({position,target})=>{camera.position.fromArray(position);orbit.target.fromArray(target);orbit.update();update();return true};
