const fs=require('node:fs/promises'),path=require('node:path'),zlib=require('node:zlib');
const {chromium}=require('/tmp/peg-final-browser/node_modules/playwright-core');
const root=path.resolve(__dirname,'../../..'),dir=path.resolve(process.env.HX_FAN_BUILD_DIR||path.join(root,'.local-runtime/stacked-fans-v1/tight-native')),out=path.resolve(process.env.HX_FAN_OUTPUT_DIR||path.join(root,'.local-runtime/stacked-fans-v1/renders'));
(async()=>{await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1200,height:850},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://spiral.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/index.html')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><script type="module" src="/gallery/vendor/model-viewer.min.js"></script><script defer src="/viewer/workbench.js"></script></head><body style="margin:0"><model-viewer id="m" style="width:100vw;height:100vh" shadow-intensity="0.7" environment-image="neutral" camera-controls></model-viewer></body></html>'});
const model=u.pathname.startsWith('/models/');const file=model?path.join(dir,u.pathname.slice(8)+'.gz'):path.join(root,'docs',u.pathname);let blob=await fs.readFile(file);if(model)blob=zlib.gunzipSync(blob);return route.fulfill({body:blob,contentType:model?'model/gltf-binary':file.endsWith('.js')?'text/javascript':'application/octet-stream'});});
await page.goto('http://spiral.test/index.html');await page.evaluate(()=>customElements.whenDefined('model-viewer'));
const ids=process.argv.slice(2).length?process.argv.slice(2):['HX05C','HX05B','HX05A','stack','empty-stack'];
for(const id of ids){const poses=id.includes('stack')?[['hero','25deg 78deg 105%',800,1300]]:[['hero','25deg 65deg 105%',1200,850],['front','0deg 90deg 105%',1200,700],['plan','0deg 0deg 105%',1200,600]];
for(const [name,orbit,width,height] of poses){await page.setViewportSize({width,height});await page.evaluate(({id,orbit})=>new Promise((resolve,reject)=>{const v=document.querySelector('#m');v.cameraOrbit=orbit;v.cameraTarget='auto auto auto';const timer=setTimeout(()=>reject(Error('Model timeout')),45000);function done(){v.cameraOrbit=orbit;v.jumpCameraToGoal();clearTimeout(timer);resolve();}v.addEventListener('load',done,{once:true});v.src=`/models/${id}.glb?pose=${Date.now()}`;}),{id,orbit});await page.waitForFunction(()=>Number(document.querySelector('#m').dataset.workbenchMaterials)>0);await page.waitForTimeout(400);await page.locator('#m').screenshot({path:path.join(out,id+'-'+name+'.jpg'),type:'jpeg',quality:86});console.log(id,name);}}
await browser.close();if(errors.length)throw Error(errors.join('\n'));})().catch(e=>{console.error(e);process.exitCode=1});
