from pathlib import Path
import json,shutil,hashlib,html
R=Path(__file__).resolve().parents[1];B=R/'bench/reviews/bespoke-tools-v1';D=R/'docs/gallery/bespoke-tools';D.mkdir(parents=True,exist_ok=True)
rows=[]
for id in ['HX01','TM01','CL01']:
 d=B/id;r=json.loads((d/'report.json').read_text());f=json.loads((d/'stiffness.json').read_text());p=json.loads((d/'toolpaths.json').read_text());g=json.loads((d/'print-geometry.json').read_text());dest=D/id;dest.mkdir(exist_ok=True)
 assert f['passed'] and g['passed']
 for mode in ['installed','print','loaded']:shutil.copyfile(d/(mode+'.glb'),dest/(mode+'.glb'))
 for role in ['installed_stl','print_stl']:shutil.copyfile(d/r['assets'][role],dest/r['assets'][role])
 evidence={k:json.loads((d/name).read_text()) for k,name in [('CAD_and_pickup','report.json'),('print_geometry','print-geometry.json'),('stiffness','stiffness.json'),('toolpaths','toolpaths.json'),('installation_screen','installation-screen.json')]}
 evidence['CAD_and_pickup'].pop('assets');evidence['CAD_and_pickup'].pop('files');evidence['physical_tests']='Pending'
 for file,key in [('external-key-fit.json','external_reference_fit'),('key-seating.json','resting_keys')]:
  if (d/file).exists():evidence[key]=json.loads((d/file).read_text())
 shutil.copyfile(d/'toolpaths.svg',dest/'toolpaths.svg')
 (dest/'checks.json').write_text(json.dumps(evidence,indent=2)+'\n')
 rows.append(dict(id=id,name=r['name'],description=r['description'],pose=r['pose'],bounds=[round(x,1) for x in r['print_bounds_mm']],time=p['time'],grams=p['extrusion_grams'],support_g=round(sum(v['grams'] for k,v in p['features'].items() if 'Support' in k),2),side=f['cases'][0]['loads'][0]['deflection_at_load_mm'],down=f['cases'][0]['loads'][1]['deflection_at_load_mm'],stl=r['assets']['print_stl']))
css='''body{margin:0;background:#edf1ee;color:#203e3a;font:16px system-ui}main{max-width:1400px;margin:auto;padding:32px}h1{font-size:36px;margin:24px 0 12px}header p{max-width:76ch;line-height:1.6}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin:28px 0}article{background:white;border:1px solid #c6d4ce;border-radius:10px;overflow:hidden}h2,p,nav{margin:18px}header nav{margin:0;display:flex;gap:24px;flex-wrap:wrap}h2{font-size:21px}model-viewer{width:100%;height:420px;background:#e0e9e4}button{background:white;border:1px solid #91ac9f;border-radius:4px;padding:9px;cursor:pointer}button[aria-pressed=true]{background:#235d50;color:white}a{color:#216255}article p{line-height:1.55;font-size:14px}.stats{font-variant-numeric:tabular-nums}.status{background:#e6ede8;padding:16px;border-radius:6px}footer{line-height:1.6}button:focus-visible,a:focus-visible{outline:3px solid #d39a38;outline-offset:3px}@media(max-width:1000px){.cards{grid-template-columns:1fr}main{padding:20px}model-viewer{height:420px}}'''
(D/'style.css').write_text(css+'\n')
intro='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>New Repro holders · thereprocase</title><link rel="stylesheet" href="style.css"><script type="module" src="../vendor/model-viewer.min.js"></script><script defer src="review.js"></script><script defer src="../../viewer/workbench.js"></script></head><body><main><header><nav aria-label="Collections"><a href="../../">Product groups</a><a href="../current-pegs/?family=repro">Repro collection</a><a href="../tool-references/">Tool reference CAD</a><a href="../cascade-funnels/">Cascading tool funnels</a></nav><h1>Three new Repro holders</h1><p>Hex keys, a tape measure and coiled leads. Each body has a broad bed face, layer-aligned lower hoops, and a short lift-and-pull pickup path.</p><p class="status">Prototype status: native CAD, mesh, clearance and linear stiffness checks pass. Local P1S / PolyLite ASA toolpaths have been reviewed. Physical print, fit and handling tests are pending.</p><p><a href="https://github.com/thereprocase/peg/releases/download/bespoke-tools-v1-2026-10-05/repro-bespoke-tools__v1__cad-source-and-review.zip">Download all three: native CAD, STL, source and checks (ZIP)</a></p></header><section class="cards" aria-label="New holder models">'''
cards=[]
for r in rows:
 id=r['id'];pose='Flat bottom' if r['pose']=='upright' else 'Right cheek';dims=' × '.join(map(str,r['bounds']))
 cards.append(f'''<article><h2>{html.escape(r['name'])}</h2><model-viewer id="{id}" src="{id}/loaded.glb" camera-controls camera-orbit="30deg 65deg auto" shadow-intensity=".4" exposure=".9" interaction-prompt="none" alt="{html.escape(r['name'])} with a gray clearance reference"></model-viewer><nav aria-label="{id} view"><button data-mode="loaded" aria-pressed="true">With reference</button><button data-mode="installed" aria-pressed="false">Empty</button><button data-mode="print" aria-pressed="false">Print pose</button></nav><p>{html.escape(r['description'])}</p><p class="stats"><strong>{pose} on the bed</strong><br>{dims} mm<br>Local slice: {r['time']} · about {r['grams']:.0f} g<br>Peg supports: {r['support_g']} g</p><p>5 N stiffness calculation: {r['side']:.3f} mm sideways, {r['down']:.3f} mm down.</p><p><a href="{id}/{r['stl']}" download>Print-oriented STL</a> · <a href="{id}/checks.json">Checks and assumptions</a> · <a href="{id}/toolpaths.svg">Support layout</a></p></article>''')
footer='''</section><footer><p>The gray shapes are clearance references: dimensioned hex-key models, a conservative tape-case envelope and a coil envelope. The tape pocket allows a case plus clip up to 92 × 48 mm; exact brand fit needs a physical check. Hex-key references and their sources are listed under <a href="../tool-references/">Tool reference CAD</a>.</p><p>Slice settings: 0.4 mm nozzle, 0.2 mm layers, two Arachne walls, 20% infill, organic supports and a 5 mm outer brim. Supports are confined behind the mounting face. The tape dock has about 0.001 g of bridge extrusion at the pointed window apex. Reslice for your printer and filament.</p><p>The stiffness calculation assumes solid isotropic ASA. Printed infill, layer bonds and board compliance affect the physical result. Check support release, spring action and tool retention on a first print.</p><p><a href="https://github.com/thereprocase/peg">Project source</a></p></footer></main></body></html>'''
(D/'index.html').write_text(intro+'\n'.join(cards)+footer)
(D/'review.js').write_text("document.querySelectorAll('article').forEach(card=>{card.querySelectorAll('button[data-mode]').forEach(button=>button.addEventListener('click',()=>{const model=card.querySelector('model-viewer');model.src=model.id+'/'+button.dataset.mode+'.glb';card.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));}));});\n")
(D/'catalog.json').write_text(json.dumps(rows,indent=2)+'\n')
receipts={p.relative_to(D).as_posix():dict(sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size) for p in D.rglob('*') if p.is_file()};(R/'publication/bespoke-tools-v1-additions.json').write_text(json.dumps(receipts,indent=2)+'\n')
print('Prepared 3 review entries and',len(receipts),'assets')
