const fs=require('node:fs/promises'),path=require('node:path'),zlib=require('node:zlib');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'/tmp/peg-final-browser/node_modules/playwright-core');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'docs/gallery/key-fan/final');
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH||'/usr/bin/chromium',headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
const page=await browser.newPage({viewport:{width:1000,height:750},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('http://final.test/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/index.html')return route.fulfill({contentType:'text/html',body:'<!doctype html><html><head><script type="module" src="/gallery/vendor/model-viewer.min.js"></script><script defer src="/viewer/workbench.js"></script></head><body style="margin:0"><model-viewer id="m" style="width:1000px;height:750px" shadow-intensity="0.8" environment-image="neutral" camera-controls></model-viewer></body></html>'});
const model=u.pathname.startsWith('/models/');const file=model?path.join(dir,u.pathname.slice(8)+'.gz'):path.join(root,'docs',u.pathname);let blob=await fs.readFile(file);if(model)blob=zlib.gunzipSync(blob);return route.fulfill({body:blob,contentType:model?'model/gltf-binary':file.endsWith('.js')?'text/javascript':'application/octet-stream'});});
await page.goto('http://final.test/index.html');await page.evaluate(()=>customElements.whenDefined('model-viewer'));
for(const id of process.argv.slice(2).length?process.argv.slice(2):['HX04','HX05A','HX05B','HX05C']){for(const [mode,name,orbit] of [['loaded','hero','30deg 65deg 110%'],['installed','empty','30deg 60deg 110%'],['print','print','35deg 60deg 110%']]){
await page.evaluate(({id,mode,orbit})=>new Promise((resolve,reject)=>{const v=document.querySelector('#m');const timer=setTimeout(()=>reject(Error('Model timeout')),45000);v.addEventListener('load',()=>{v.cameraOrbit=orbit;v.cameraTarget='auto auto auto';v.jumpCameraToGoal();clearTimeout(timer);resolve()},{once:true});v.src=`/models/${id}/${mode}.glb`; }),{id,mode,orbit});await page.waitForFunction(()=>Number(document.querySelector('#m').dataset.workbenchMaterials)>0);await page.waitForTimeout(600);await page.locator('#m').screenshot({path:path.join(dir,id,name+'.jpg'),type:'jpeg',quality:82});console.log(id,name);}}
await browser.close();if(errors.length)throw Error(errors.join('\n'));})().catch(e=>{console.error(e);process.exitCode=1});
